[phases.setup]
nixPkgs = ["chromium"]

[phases.install]
cmds = ["npm ci"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/var/nix/profiles/default/bin/chromium"
